#!/usr/bin/env python3
"""Guarded launcher for review-only workflow dispatch payload artifacts.

Default mode is dry-run. The tool only writes an execution plan and equivalent
commands. Actual GitHub workflow dispatch requires both --execute and an exact
approval token, and it refuses payloads that allow production mutation.
"""
from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPO = Path(__file__).resolve().parent.parent
APPROVAL_TOKEN = "APPROVE_REVIEW_WORKFLOW_DISPATCH"
ALLOWED_WORKFLOWS = {
    "full_rebuild_manual.yml",
    "free_data_lake_bootstrap.yml",
    "adr_candidate_monthly.yml",
    "data_readiness_preflight.yml",
}


def repo_path(value: str | Path) -> Path:
    path = Path(value)
    return path if path.is_absolute() else REPO / path


def read_payloads(path: Path) -> list[dict[str, Any]]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise ValueError(f"cannot read payload JSON: {path}: {exc}") from exc
    if not isinstance(payload, list):
        raise ValueError(f"payload JSON must be a list: {path}")
    rows: list[dict[str, Any]] = []
    for item in payload:
        if isinstance(item, dict):
            rows.append(item)
    return rows


def payload_id(payload: dict[str, Any], index: int = 0) -> str:
    for key in ("plan_id", "experiment_id", "id"):
        value = payload.get(key)
        if value:
            return str(value)
    return f"payload_{index + 1}"


def validate_payload(payload: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    workflow_id = str(payload.get("workflow_id") or "")
    inputs = payload.get("inputs")
    if workflow_id not in ALLOWED_WORKFLOWS:
        errors.append(f"workflow_not_allowed:{workflow_id or 'missing'}")
    if not isinstance(inputs, dict):
        errors.append("inputs_not_object")
    if payload.get("requires_user_approval") is not True:
        errors.append("requires_user_approval_not_true")
    if payload.get("production_mutation_allowed") is not False:
        errors.append("production_mutation_allowed_not_false")
    return errors


def workflow_args(payload: dict[str, Any], repo: str, gh_bin: str) -> list[str]:
    args = [
        gh_bin,
        "workflow",
        "run",
        str(payload.get("workflow_id") or ""),
        "--repo",
        repo,
        "--ref",
        str(payload.get("ref") or "master"),
    ]
    for key, value in sorted((payload.get("inputs") or {}).items()):
        args.extend(["-f", f"{key}={value}"])
    return args


def shell_command(args: list[str]) -> str:
    return " ".join(shlex.quote(str(part)) for part in args)


def build_plan(
    payloads: list[dict[str, Any]],
    *,
    repo: str,
    gh_bin: str,
    only: set[str],
    completed_plan_ids: set[str],
) -> list[dict[str, Any]]:
    selected_rows: list[dict[str, Any]] = []
    selected_ids = {payload_id(row, idx) for idx, row in enumerate(payloads) if not only or payload_id(row, idx) in only}
    for idx, payload in enumerate(payloads):
        item_id = payload_id(payload, idx)
        if only and item_id not in only:
            continue
        errors = validate_payload(payload)
        dependencies = [str(item) for item in payload.get("depends_on_plan_ids") or []]
        unmet_dependencies = [
            item for item in dependencies if item not in completed_plan_ids
        ]
        if unmet_dependencies:
            errors.append("unmet_dependencies:" + ",".join(unmet_dependencies))
        status = "ready" if not errors else "blocked"
        selected_rows.append(
            {
                "id": item_id,
                "status": status,
                "errors": errors,
                "workflow_id": payload.get("workflow_id"),
                "ref": payload.get("ref") or "master",
                "dependencies": dependencies,
                "unmet_dependencies": unmet_dependencies,
                "selected_dependency_ids": sorted(set(dependencies).intersection(selected_ids)),
                "requires_user_approval": payload.get("requires_user_approval"),
                "production_mutation_allowed": payload.get("production_mutation_allowed"),
                "command": shell_command(workflow_args(payload, repo, gh_bin)) if status == "ready" else "",
                "payload": payload,
            }
        )
    return selected_rows


def render_commands(plan_rows: list[dict[str, Any]]) -> str:
    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by run_review_dispatcher.py. Review before running.",
        "",
    ]
    for row in plan_rows:
        if row["status"] != "ready":
            lines.append(f"# blocked: {row['id']} ({'; '.join(row['errors'])})")
            lines.append("")
            continue
        lines.append("# " + str(row["id"]))
        lines.append(str(row["command"]))
        lines.append("")
    return "\n".join(lines)


def render_markdown(summary: dict[str, Any]) -> str:
    lines = [
        "# Review Workflow Dispatch Plan",
        "",
        f"- status: `{summary.get('status')}`",
        f"- execute_requested: `{str(summary.get('execute_requested')).lower()}`",
        f"- dispatched_count: `{summary.get('dispatched_count')}`",
        f"- ready_count: `{summary.get('ready_count')}`",
        f"- blocked_count: `{summary.get('blocked_count')}`",
        "",
        "| ID | Status | Workflow | Errors |",
        "| --- | --- | --- | --- |",
    ]
    for row in summary.get("plan_rows") or []:
        errors = ", ".join(row.get("errors") or [])
        lines.append(f"| {row.get('id')} | {row.get('status')} | {row.get('workflow_id')} | {errors} |")
    lines.append("")
    return "\n".join(lines)


def dispatch_ready_rows(plan_rows: list[dict[str, Any]], *, repo: str, gh_bin: str) -> list[dict[str, Any]]:
    dispatched: list[dict[str, Any]] = []
    for row in plan_rows:
        payload = row["payload"]
        args = workflow_args(payload, repo, gh_bin)
        proc = subprocess.run(args, capture_output=True, text=True, encoding="utf-8", errors="replace")
        dispatched.append(
            {
                "id": row["id"],
                "returncode": proc.returncode,
                "stdout": proc.stdout.strip(),
                "stderr": proc.stderr.strip(),
                "command": shell_command(args),
            }
        )
        if proc.returncode != 0:
            break
    return dispatched


def run(args: argparse.Namespace) -> dict[str, Any]:
    payload_path = repo_path(getattr(args, "payloads", "outputs/system_acceptance_audit/workflow_dispatch_payloads.json"))
    output_dir = repo_path(getattr(args, "output_dir", "outputs/review_dispatcher"))
    repo = str(getattr(args, "repo", "wscha231/r1000-quant-engine"))
    gh_bin = str(getattr(args, "gh_bin", "gh"))
    only = {str(item) for item in (getattr(args, "only", None) or [])}
    completed_plan_ids = {str(item) for item in (getattr(args, "completed_plan_id", None) or [])}
    execute = bool(getattr(args, "execute", False))
    approval_token = str(getattr(args, "approval_token", "") or "")

    payloads = read_payloads(payload_path)
    plan_rows = build_plan(payloads, repo=repo, gh_bin=gh_bin, only=only, completed_plan_ids=completed_plan_ids)
    ready_rows = [row for row in plan_rows if row["status"] == "ready"]
    blocked_rows = [row for row in plan_rows if row["status"] != "ready"]
    dispatched: list[dict[str, Any]] = []
    refusal_reason = ""
    status = "dry_run_ready" if not blocked_rows else "dry_run_blocked"

    if execute:
        if approval_token != APPROVAL_TOKEN:
            status = "refused"
            refusal_reason = "approval_token_mismatch"
        elif blocked_rows:
            status = "refused"
            refusal_reason = "selected_payloads_blocked"
        else:
            dispatched = dispatch_ready_rows(ready_rows, repo=repo, gh_bin=gh_bin)
            failed = [row for row in dispatched if row.get("returncode") != 0]
            status = "dispatch_failed" if failed else "dispatched"

    summary = {
        "schema_version": "review-dispatcher-v1",
        "generated_at_utc": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "payloads_path": str(payload_path),
        "status": status,
        "refusal_reason": refusal_reason,
        "execute_requested": execute,
        "approval_token_required": APPROVAL_TOKEN,
        "repo": repo,
        "selected_count": len(plan_rows),
        "ready_count": len(ready_rows),
        "blocked_count": len(blocked_rows),
        "dispatched_count": len([row for row in dispatched if row.get("returncode") == 0]),
        "plan_rows": plan_rows,
        "dispatch_results": dispatched,
    }
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "summary.json").write_text(json.dumps(summary, indent=2, sort_keys=True, default=str) + "\n", encoding="utf-8")
    (output_dir / "dispatch_commands.sh").write_text(render_commands(plan_rows) + "\n", encoding="utf-8")
    (output_dir / "report.md").write_text(render_markdown(summary), encoding="utf-8")
    print(json.dumps({"status": status, "ready": len(ready_rows), "blocked": len(blocked_rows), "dispatched": summary["dispatched_count"]}, indent=2))
    return summary


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--payloads", default="outputs/system_acceptance_audit/workflow_dispatch_payloads.json")
    parser.add_argument("--output-dir", default="outputs/review_dispatcher")
    parser.add_argument("--repo", default="wscha231/r1000-quant-engine")
    parser.add_argument("--gh-bin", default="gh")
    parser.add_argument("--only", action="append", default=[])
    parser.add_argument("--completed-plan-id", action="append", default=[])
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--approval-token", default="")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    summary = run(parse_args(argv))
    if summary["status"] in {"refused", "dispatch_failed"}:
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
