"""Build proposal-only AutoLearning v2 policy candidates."""
from __future__ import annotations

from typing import Any

from r1000_auto_learning_policy import render_policy_yaml

from .policy_grammar import make_base_candidate, validate_policy_candidate


def build_policy_candidate(
    anomalies: list[dict[str, Any]],
    hypotheses: list[dict[str, Any]],
    novelty_report: dict[str, Any],
    counterfactuals: list[dict[str, Any]],
) -> dict[str, Any]:
    candidate = make_base_candidate()
    candidate["novelty_regime"] = novelty_report
    candidate["anomalies"] = [
        {
            "id": item.get("id"),
            "category": item.get("category"),
            "severity": item.get("severity"),
            "confidence": item.get("confidence"),
            "observation": item.get("observation"),
            "breaks_assumption": item.get("breaks_assumption"),
        }
        for item in anomalies
    ]
    candidate["hypotheses"] = hypotheses
    candidate["policy_candidates"] = [
        {
            "id": hypothesis.get("id"),
            "status": hypothesis.get("status"),
            "hypothesis": hypothesis.get("hypothesis"),
            "rules": hypothesis.get("rules") or [],
            "test_plan": hypothesis.get("test_plan") or {},
            "exploration_budget": hypothesis.get("exploration_budget") or {"stage": "shadow", "capital_weight": 0.0},
        }
        for hypothesis in hypotheses
    ]
    candidate["counterfactuals"] = counterfactuals
    candidate["validation"] = validate_policy_candidate(candidate)
    return candidate


def render_candidate_yaml(candidate: dict[str, Any]) -> str:
    text = render_policy_yaml(candidate)
    return text.replace(
        "# AUTO-GENERATED by tools/auto_policy_proposal.py.",
        "# AUTO-GENERATED by tools/run_auto_learning_v2.py.",
        1,
    )
